---
ci:
  - ".github/workflows/**"
  - ".github/*.yml"
  - ".yamllint.yaml"
  - ".pre-commit-config.yaml"

docs:
  - "*.md"
  - "docs/**"
  - "**/README.md"
  - "**/CONTRIBUTING.md"

meta:
  - ".github/**"
  - ".gitignore"
  - ".gitattributes"
  - ".editorconfig"
  - ".tool-versions"
  - ".envrc"

stack:
  - "stack/**"
  - "docker-compose*.yml"

docker:
  - "Dockerfile"
  - "**/Dockerfile"
  - "stack/**/*.env"
  - "stack/**/*.dockerfile"

config:
  - ".env"
  - ".env.*"
  - "stack/.env"
  - "stack/.env.*"
  - "Makefile"
  - "justfile"

dependencies:
  - "requirements.txt"
  - "poetry.lock"
  - "pyproject.toml"
  - "stack/**/Dockerfile"
  - "**/package*.json"
