---
name: Mark stale issues and pull requests

"on":
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "Inactive issue. Will auto-close soon unless there's new activity."
          stale-pr-message: "Inactive PR. Will auto-close soon unless there's new activity."
          stale-issue-label: stale
          stale-pr-label: stale
