---
name: Mark Stale Issues and PRs

"on":
  schedule:
    - cron: '0 0 * * *'  # daily

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            Issue stale due to inactivity. It will be closed soon if no further activity.
          stale-pr-message: >
            PR stale due to inactivity. It will be closed soon if no further activity.
          stale-issue-label: stale
          stale-pr-label: stale
          days-before-stale: 30
          days-before-close: 7
