---
name: Full Validation

"on":
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint stack/

      - name: Validate docker-compose file
        run: docker compose -f stack/docker-compose.yml config

      - name: Trivy IaC Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: stack/
